#pragma once
#include <citro2d.h>
#include <3ds.h>

#define CLEAR_COLOR 0x323353FF
#define CLOSE_LINE_COLOR 0xffffffff
#define FAR_LINE_COLOR 0x000000ff

#define DISPLAY_TRANSFER_FLAGS \
	(GX_TRANSFER_FLIP_VERT(0) | GX_TRANSFER_OUT_TILED(0) | GX_TRANSFER_RAW_COPY(0) | \
	GX_TRANSFER_IN_FORMAT(GX_TRANSFER_FMT_RGBA8) | GX_TRANSFER_OUT_FORMAT(GX_TRANSFER_FMT_RGB8) | \
	GX_TRANSFER_SCALING(GX_TRANSFER_SCALE_NO))

#define SCREEN_WIDTH_TOP  400
#define SCREEN_HEIGHT_TOP 240
#define SCREEN_WIDTH_BOT  320
#define SCREEN_HEIGHT_BOT 240

#define MAX_VERTEX 100


#define EDITOR_BAR_X 276
#define EDITOR_BAR_Y 0
#define EDITOR_BAR_W 44
#define EDITOR_BAR_H 240

#define PRO_C1_X 21
#define PRO_C1_Y 2
#define PRO_C2_X 256
#define PRO_C2_Y 237